#!/usr/bin/env bash
# Script to display time from 0 to 12 hours and 1 to 59 minutes using a while loop
hour=0

while [ $hour -le 12 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
